project:
  type: website

website:
  title: "☸️"
  favicon: "☸️"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    background: light 
    center: 
      - text: reAUGMENT AI (UG)
        file: index.qmd
      - text: Imprint
        file: about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: false
    fontsize: large
    page-layout: full
    



