project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "☸️"
  favicon: "☸️"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    background: light 
    center: 
      - text: Reaugment AI (UG)
        file: index.qmd
      - text: Imprint
        file: about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: false
    fontsize: large
    page-layout: full
    grid: 
      body-width: 1600px
      margin-width: 0px
      sidebar-width: 0px
      gutter-width: 0em
    



