project:
  type: website

website:
  title: "☸️"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    fontsize: large
    page-layout: full
    



